[mypy]
python_version = 3.12
warn_return_any = False
warn_unused_configs = True
disable_error_code = import-untyped
plugins = pydantic.mypy

[mypy-grpc.*]
ignore_missing_imports = True

[mypy-torch.*]
ignore_missing_imports = True

[mypy-prometheus_client.*]
ignore_missing_imports = True

[mypy-stashify_protos.*]
ignore_missing_imports = True

[mypy-deprecated.*]
ignore_missing_imports = True

[mypy-mrflagly.*]
ignore_missing_imports = True

[mypy-fire.*]
ignore_missing_imports = True

[mypy-pytest_docker_fixtures.*]
ignore_missing_imports = True

[mypy-sqlalchemy_utils.*]
ignore_missing_imports = True

[mypy-requests.*]
ignore_missing_imports = True
