[build-system]
requires = ["setuptools >= 64"]
build-backend = "setuptools.build_meta"

[project]
name = "hyperforge"
version = "1.0.0"
authors = [{ name = "AI Data Team", email = "learning@nuclia.com" }]
description = "Agentic Framework for Orchestrated Runtime, Governance, and Execution"
readme = "README.md"
requires-python = ">=3.10"
classifiers = [
    "Programming Language :: Python :: 3",
    "Operating System :: OS Independent",
]
license = "Apache-2.0"
dependencies = [
    "alembic",
    "pydantic",
    "nuclia>=4.9.25",
    "nuclia-models>=0.52.1",
    "nucliadb-models>=6.13.1.post6414",
    "nucliadb-sdk>=6.13.1.post6414",
    "nucliadb-telemetry[otel]",
    "pydantic_settings",
    "mcp>=1.26.0",
    "prometheus_client",
    "mrflagly>=0.2.11",
    "aiodns",
    "httpx",
    "jinja2",
    "databases[asyncpg]",
    "sqlalchemy",
    "cryptography",
    "mmh3",
    "psycopg2",
    "tenacity",
    "websockets",
    "redis[hiredis]>=6.4.0",
    "types-redis>=4.6.0.20241004",
    "ruff>=0.15.10",
    "lru-dict",
    "sentry_sdk",
    "fastapi",
]


[dependency-groups]
dev = [
    "pytest",
    "pytest-asyncio",
    "pytest-cov",
    "pytest-mock",
    "pytest-benchmark",
    "pytest-docker-fixtures>=1.4.2",
    "pytest-lazy-fixtures",
    "httpx[http2]",
    "hyperforge_rephrase",
    "inline_snapshot",
    "sqlalchemy_utils",
]

[tool.setuptools.packages.find]
where = ["src/"]

[tool.setuptools.package-data]
hyperforge = ["frontend/dist/*"]

[project.urls]
"Progress" = "https://progress.com"
"Github" = "https://github.com/nuclia/forge"
"API Reference" = "https://docs.rag.progress.cloud"

[tool.pytest.ini_options]
asyncio_mode = "auto"


[project.scripts]
hyperforge-api = "hyperforge.api:commands.run"
hyperforge-server = "hyperforge.server:run.run"
hyperforge-sandbox = "hyperforge.sandbox:run.run"
hyperforge-extract-openapi = "hyperforge.api.commands:extract_openapi"
hyperforge-downloads-cronjob = "hyperforge.downloads.command:run"
hyperforge-workflows-cleanup-cronjob = "hyperforge.agents.workflow_cleanup:run"
hyperforge-standalone = "hyperforge.standalone:run.run"
