from typing import Any, Dict, Optional, Tuple

from pydantic import (
    AliasChoices,
    BaseModel,
    Field,
    ValidationError,
    ValidatorFunctionWrapHandler,
    field_serializer,
    field_validator,
)

from hyperforge.agent import AgentConfig
from hyperforge.configure import get_agent_config_klass
from hyperforge.utils import WidgetType


def context_agent_validator(value: Any, handler: ValidatorFunctionWrapHandler) -> str:
    try:
        return handler(value)
    except ValidationError as err:
        if err.errors()[0]["type"] == "string_too_long":
            return handler(value[:5])
        else:
            raise


class ContextAgentConfig(AgentConfig):
    fallback: Optional["ContextAgentConfig"] = Field(
        default=None,
        title="Fallback agent",
        description="Agent to use in case this one fails",
        json_schema_extra={
            "widget": WidgetType.NOT_SHOWN,
        },
    )
    next_agent: Optional["ContextAgentConfig"] = Field(
        default=None,
        title="Next agent",
        description="Agent to run after executing the code",
        json_schema_extra={
            "widget": WidgetType.NOT_SHOWN,
        },
    )
    context_validation_model: str = Field(
        default="chatgpt-azure-4o-mini",
        title="Context validation model",
        description="Model used to validate the agent's generated context and generate an answer attempt to the user's question.",
        json_schema_extra={"widget": WidgetType.MODEL_SELECT},
        # Backward compatibility with frontend and stored configurations
        validation_alias=AliasChoices("context_validation_model", "summarize_model"),
    )
    rephrase_model: str = Field(
        default="chatgpt-azure-4o-mini",
        title="Rephrase model",
        description="Model used to rephrase the question based on context (only used in agents that follow others in a chain)",
        json_schema_extra={"widget": WidgetType.MODEL_SELECT},
    )
    context_aware_rephrasing_prompt: Optional[str] = Field(
        default=None,
        title="Context-aware rephrasing prompt",
        description="Custom prompt to give the model when rephrasing questions based on previous contexts (only used in agents that follow others in a chain)",
        json_schema_extra={
            "widget": WidgetType.EXPANDABLE_TEXTAREA,
        },
    )
    prune_context: bool = Field(
        default=True,
        title="Prune context",
        description="Whether to prune the context pieces generated by this agent before storing them in memory. Will always trigger a context validation call if enabled.",
    )

    published_functions: Optional[Tuple[str, ...]] = Field(
        default=None,
        title="Published functions",
        description="List of functions published by this agent to be used by other agents in the chain",
        json_schema_extra={
            "widget": WidgetType.NOT_SHOWN,
        },
    )
    # always_validate_contexts: bool = Field(
    #     default=False,
    #     title="Always validate and attempt to generate an answer",
    #     description="Whether to always validate the context retrieved and attempt to generate an answer to the question with this agent's context. Regardless if it is not required for pruning or for the next agent in the chain.",
    # )

    @field_validator("fallback", "next_agent", mode="before")
    @classmethod
    def is_context_agent(cls, value: Dict[str, Any]) -> BaseModel:
        if value is None:
            return value
        module = value.get("module")
        if module is None:
            raise ValueError("Invalid agent config: missing 'module' field")

        agent_config_klass = get_agent_config_klass(module, agent_type="context")
        return agent_config_klass.model_validate(value)

    @field_serializer("fallback", "next_agent")
    def serialize_context_agent(self, field: BaseModel) -> Optional[Dict[str, Any]]:
        if field is None:
            return field
        return field.model_dump()
