[project]
dependencies = ["hyperforge"]

name = "hyperforge_static_string"
version = "0.0.1"
authors = []
description = "A Hyperforge agent that always returns a fixed string"
requires-python = ">=3.12"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]
license = { text = "MIT License" }

[tool.uv]
required-version = ">=0.10"
managed = true
default-groups = "all"
keyring-provider = "subprocess"
package = true

[project.urls]
Homepage = "https://progress.com"
Changelog = "https://github.com/nuclia/hyperforge/blob/main/agents/static_string/CHANGELOG.md"

[tool.pytest.ini_options]
asyncio_mode = "auto"

[tool.uv.build-backend]

# Exclude specific files from being packaged
source-exclude = ["tests/**", "*.pyc"]

[dependency-groups]
dev = [
    "pytest",
    "pytest-asyncio",
]

[tool.ruff]
extend = "../../ruff.toml"
