"""Add download requests table

Revision ID: 1416cb41bd49
Revises: 4d89a36c8bda
Create Date: 2026-01-19 12:28:08.779660

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "1416cb41bd49"
down_revision: Union[str, None] = "4d89a36c8bda"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "download_requests",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("account_id", sa.String(), nullable=False),
        sa.Column("requested_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("type", sa.String(), nullable=False),
        sa.Column("query", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("content_type", sa.String(), nullable=True),
        sa.Column("signed_url", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_download_requests_account_id"),
        "download_requests",
        ["account_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_download_requests_type"), "download_requests", ["type"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_download_requests_type"), table_name="download_requests")
    op.drop_index(
        op.f("ix_download_requests_account_id"), table_name="download_requests"
    )
    op.drop_table("download_requests")
    # ### end Alembic commands ###
