"""unique_driver

Revision ID: 2847934e2d59
Revises: 72b997edb05d
Create Date: 2025-08-07 13:17:56.145551

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "2847934e2d59"
down_revision: Union[str, None] = "72b997edb05d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "retrieval_agents_drivers",
        "identifier",
        existing_type=sa.VARCHAR(),
        nullable=False,
    )
    op.drop_index(
        op.f("ix_retrieval_agents_drivers_account"),
        table_name="retrieval_agents_drivers",
    )
    op.drop_index(
        op.f("ix_retrieval_agents_drivers_config"),
        table_name="retrieval_agents_drivers",
    )
    op.drop_index(
        op.f("ix_retrieval_agents_drivers_driver"),
        table_name="retrieval_agents_drivers",
    )
    op.drop_index(
        op.f("ix_retrieval_agents_drivers_kbid"), table_name="retrieval_agents_drivers"
    )
    op.drop_index(
        op.f("ix_retrieval_agents_drivers_provider"),
        table_name="retrieval_agents_drivers",
    )
    op.create_unique_constraint(
        None, "retrieval_agents_drivers", ["account", "kbid", "identifier"]
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "retrieval_agents_drivers", type_="unique")  # type: ignore[arg-type]  # ty: ignore[invalid-argument-type]
    op.create_index(
        op.f("ix_retrieval_agents_drivers_provider"),
        "retrieval_agents_drivers",
        ["provider"],
        unique=False,
    )
    op.create_index(
        op.f("ix_retrieval_agents_drivers_kbid"),
        "retrieval_agents_drivers",
        ["kbid"],
        unique=False,
    )
    op.create_index(
        op.f("ix_retrieval_agents_drivers_driver"),
        "retrieval_agents_drivers",
        ["driver"],
        unique=False,
    )
    op.create_index(
        op.f("ix_retrieval_agents_drivers_config"),
        "retrieval_agents_drivers",
        ["config"],
        unique=False,
    )
    op.create_index(
        op.f("ix_retrieval_agents_drivers_account"),
        "retrieval_agents_drivers",
        ["account"],
        unique=False,
    )
    op.alter_column(
        "retrieval_agents_drivers",
        "identifier",
        existing_type=sa.VARCHAR(),
        nullable=True,
    )
    # ### end Alembic commands ###
