"""empty message

Revision ID: b8edb72295e0
Revises:
Create Date: 2025-04-11 21:24:17.278970

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "b8edb72295e0"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.execute('CREATE EXTENSION IF NOT EXISTS "uuid-ossp";')
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "retrieval_agent_config",
        sa.Column("account", sa.String(), nullable=False),
        sa.Column("kbid", sa.String(), nullable=False),
        sa.Column("rules", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("created", sa.DateTime(), default=sa.func.now()),
        sa.Column("modified", sa.DateTime(), onupdate=sa.func.now()),
        sa.PrimaryKeyConstraint("account", "kbid"),
    )
    op.create_index(
        op.f("ix_retrieval_agent_config_account"),
        "retrieval_agent_config",
        ["account"],
        unique=False,
    )
    op.create_index(
        op.f("ix_retrieval_agent_config_kbid"),
        "retrieval_agent_config",
        ["kbid"],
        unique=False,
    )
    op.create_table(
        "retrieval_agent_config_activity",
        sa.Column("account", sa.String(), nullable=False),
        sa.Column("kbid", sa.String(), nullable=False),
        sa.Column("userid", sa.String(), nullable=False),
        sa.Column("activity", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("created", sa.DateTime(), default=sa.func.now()),
        sa.Column("modified", sa.DateTime(), onupdate=sa.func.now()),
        sa.ForeignKeyConstraint(
            ["account", "kbid"],
            ["retrieval_agent_config.account", "retrieval_agent_config.kbid"],
            onupdate="CASCADE",
            ondelete="CASCADE",
        ),
    )
    op.create_index(
        op.f("ix_retrieval_agent_config_activity_account"),
        "retrieval_agent_config_activity",
        ["account"],
        unique=False,
    )
    op.create_index(
        op.f("ix_retrieval_agent_config_activity_kbid"),
        "retrieval_agent_config_activity",
        ["kbid"],
        unique=False,
    )
    op.create_index(
        op.f("ix_retrieval_agent_config_activity_userid"),
        "retrieval_agent_config_activity",
        ["userid"],
        unique=False,
    )
    op.create_table(
        "retrieval_agent_context",
        sa.Column(
            "id",
            postgresql.UUID(),
            server_default=sa.func.uuid_generate_v4(),
            nullable=False,
        ),
        sa.Column("account", sa.String(), nullable=False),
        sa.Column("kbid", sa.String(), nullable=False),
        sa.Column("context", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("created", sa.DateTime(), default=sa.func.now()),
        sa.Column("modified", sa.DateTime(), onupdate=sa.func.now()),
        sa.ForeignKeyConstraint(
            ["account", "kbid"],
            ["retrieval_agent_config.account", "retrieval_agent_config.kbid"],
            onupdate="CASCADE",
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_retrieval_agent_context_account"),
        "retrieval_agent_context",
        ["account"],
        unique=False,
    )
    op.create_index(
        op.f("ix_retrieval_agent_context_kbid"),
        "retrieval_agent_context",
        ["kbid"],
        unique=False,
    )
    op.create_table(
        "retrieval_agent_postprocess",
        sa.Column(
            "id",
            postgresql.UUID(),
            server_default=sa.func.uuid_generate_v4(),
            nullable=False,
        ),
        sa.Column("account", sa.String(), nullable=False),
        sa.Column("kbid", sa.String(), nullable=False),
        sa.Column(
            "postprocess", postgresql.JSONB(astext_type=sa.Text()), nullable=False
        ),
        sa.Column("created", sa.DateTime(), default=sa.func.now()),
        sa.Column("modified", sa.DateTime(), onupdate=sa.func.now()),
        sa.ForeignKeyConstraint(
            ["account", "kbid"],
            ["retrieval_agent_config.account", "retrieval_agent_config.kbid"],
            onupdate="CASCADE",
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_retrieval_agent_postprocess_account"),
        "retrieval_agent_postprocess",
        ["account"],
        unique=False,
    )
    op.create_index(
        op.f("ix_retrieval_agent_postprocess_kbid"),
        "retrieval_agent_postprocess",
        ["kbid"],
        unique=False,
    )
    op.create_table(
        "retrieval_agent_preprocess",
        sa.Column(
            "id",
            postgresql.UUID(),
            server_default=sa.func.uuid_generate_v4(),
            nullable=False,
        ),
        sa.Column("account", sa.String(), nullable=False),
        sa.Column("kbid", sa.String(), nullable=False),
        sa.Column(
            "preprocess", postgresql.JSONB(astext_type=sa.Text()), nullable=False
        ),
        sa.Column("created", sa.DateTime(), default=sa.func.now()),
        sa.Column("modified", sa.DateTime(), onupdate=sa.func.now()),
        sa.ForeignKeyConstraint(
            ["account", "kbid"],
            ["retrieval_agent_config.account", "retrieval_agent_config.kbid"],
            onupdate="CASCADE",
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_retrieval_agent_preprocess_account"),
        "retrieval_agent_preprocess",
        ["account"],
        unique=False,
    )
    op.create_index(
        op.f("ix_retrieval_agent_preprocess_kbid"),
        "retrieval_agent_preprocess",
        ["kbid"],
        unique=False,
    )
    op.create_table(
        "retrieval_agents_drivers",
        sa.Column(
            "id",
            postgresql.UUID(),
            server_default=sa.func.uuid_generate_v4(),
            nullable=False,
        ),
        sa.Column("account", sa.String(), nullable=False),
        sa.Column("kbid", sa.String(), nullable=False),
        sa.Column("driver", sa.String(), nullable=False),
        sa.Column("provider", sa.String(), nullable=False),
        sa.Column("config", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("created", sa.DateTime(), default=sa.func.now()),
        sa.Column("modified", sa.DateTime(), onupdate=sa.func.now()),
        sa.ForeignKeyConstraint(
            ["account", "kbid"],
            ["retrieval_agent_config.account", "retrieval_agent_config.kbid"],
            onupdate="CASCADE",
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_retrieval_agents_drivers_account"),
        "retrieval_agents_drivers",
        ["account"],
        unique=False,
    )
    op.create_index(
        op.f("ix_retrieval_agents_drivers_config"),
        "retrieval_agents_drivers",
        ["config"],
        unique=False,
    )
    op.create_index(
        op.f("ix_retrieval_agents_drivers_driver"),
        "retrieval_agents_drivers",
        ["driver"],
        unique=False,
    )
    op.create_index(
        op.f("ix_retrieval_agents_drivers_kbid"),
        "retrieval_agents_drivers",
        ["kbid"],
        unique=False,
    )
    op.create_index(
        op.f("ix_retrieval_agents_drivers_provider"),
        "retrieval_agents_drivers",
        ["provider"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_retrieval_agents_drivers_provider"),
        table_name="retrieval_agents_drivers",
    )
    op.drop_index(
        op.f("ix_retrieval_agents_drivers_kbid"), table_name="retrieval_agents_drivers"
    )
    op.drop_index(
        op.f("ix_retrieval_agents_drivers_driver"),
        table_name="retrieval_agents_drivers",
    )
    op.drop_index(
        op.f("ix_retrieval_agents_drivers_config"),
        table_name="retrieval_agents_drivers",
    )
    op.drop_index(
        op.f("ix_retrieval_agents_drivers_account"),
        table_name="retrieval_agents_drivers",
    )
    op.drop_table("retrieval_agents_drivers")
    op.drop_index(
        op.f("ix_retrieval_agent_preprocess_kbid"),
        table_name="retrieval_agent_preprocess",
    )
    op.drop_index(
        op.f("ix_retrieval_agent_preprocess_account"),
        table_name="retrieval_agent_preprocess",
    )
    op.drop_table("retrieval_agent_preprocess")
    op.drop_index(
        op.f("ix_retrieval_agent_postprocess_kbid"),
        table_name="retrieval_agent_postprocess",
    )
    op.drop_index(
        op.f("ix_retrieval_agent_postprocess_account"),
        table_name="retrieval_agent_postprocess",
    )
    op.drop_table("retrieval_agent_postprocess")
    op.drop_index(
        op.f("ix_retrieval_agent_context_kbid"), table_name="retrieval_agent_context"
    )
    op.drop_index(
        op.f("ix_retrieval_agent_context_account"), table_name="retrieval_agent_context"
    )
    op.drop_table("retrieval_agent_context")
    op.drop_index(
        op.f("ix_retrieval_agent_config_activity_userid"),
        table_name="retrieval_agent_config_activity",
    )
    op.drop_index(
        op.f("ix_retrieval_agent_config_activity_kbid"),
        table_name="retrieval_agent_config_activity",
    )
    op.drop_index(
        op.f("ix_retrieval_agent_config_activity_account"),
        table_name="retrieval_agent_config_activity",
    )
    op.drop_table("retrieval_agent_config_activity")
    op.drop_index(
        op.f("ix_retrieval_agent_config_kbid"), table_name="retrieval_agent_config"
    )
    op.drop_index(
        op.f("ix_retrieval_agent_config_account"), table_name="retrieval_agent_config"
    )
    op.drop_table("retrieval_agent_config")
    # ### end Alembic commands ###
