import asyncio
import base64
import hashlib
import secrets
import ssl
import tempfile
from collections.abc import Awaitable, Callable
from functools import cache, partial
from typing import Any, Optional
from urllib.parse import parse_qs, urlencode, urlparse
from uuid import uuid4

import httpx
from cryptography.fernet import Fernet
from httpx import Auth, Timeout
from mcp.client.auth import OAuthClientProvider, PKCEParameters, TokenStorage
from mcp.client.auth.exceptions import OAuthFlowError
from mcp.client.streamable_http import streamable_http_client
from mcp.shared.auth import (
    OAuthClientInformationFull,
    OAuthClientMetadata,
    OAuthMetadata,
    OAuthToken,
)
from pydantic import AnyUrl, BaseModel

from hyperforge import logger
from hyperforge.configure import driver
from hyperforge.driver import Driver
from hyperforge.interaction import (
    Feedback,
    OAuthAuthenticateURL,
    OAuthFeedbackReturnSchema,
    Provider,
)
from hyperforge.memory import QuestionMemory
from hyperforge.utils.http import SafeTransport
from hyperforge_mcp.config_driver import MCPHTTPDriverConfig, MCPHTTPInnerConfig

# ---------------------------------------------------------------------------
# Stateless MCP OAuth state - Fernet-encrypted routing context
# ---------------------------------------------------------------------------
# The PKCE ``state`` parameter generated by the SDK is replaced with a
# Fernet token that contains the routing context (account_id, session_id,
# etc.) encrypted and signed.
# ---------------------------------------------------------------------------

_MCP_OAUTH_STATE_TTL = 600  # seconds - max age for the Fernet token
_MCP_OAUTH_SINGLE_FLIGHT_LOCKS: dict[str, asyncio.Lock] = {}
_PKCE_VERIFIER_ALPHABET = (
    "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789"
)


def _get_single_flight_lock(key: str) -> asyncio.Lock:
    lock = _MCP_OAUTH_SINGLE_FLIGHT_LOCKS.get(key)
    if lock is None:
        lock = asyncio.Lock()
        _MCP_OAUTH_SINGLE_FLIGHT_LOCKS[key] = lock
    return lock


def _fingerprint(value: str) -> str:
    return hashlib.sha256(value.encode()).hexdigest()[:12]


def _pkce_challenge_for_verifier(code_verifier: str) -> str:
    digest = hashlib.sha256(code_verifier.encode()).digest()
    return base64.urlsafe_b64encode(digest).decode().rstrip("=")


def _generate_pkce_parameters() -> PKCEParameters:
    code_verifier = "".join(secrets.choice(_PKCE_VERIFIER_ALPHABET) for _ in range(128))
    return PKCEParameters(
        code_verifier=code_verifier,
        code_challenge=_pkce_challenge_for_verifier(code_verifier),
    )


class MCPOAuthRoutingParams(BaseModel):
    """Routing context embedded in the OAuth state parameter.

    Carries the identifiers needed by the callback endpoint to reconstruct
    the NATS subject and route the token back to the originating request.
    """

    account_id: str
    agent_id: str
    workflow_id: str
    session_id: str
    question_id: str
    oauth_uuid: str
    sdk_state: str = ""

    @classmethod
    def from_memory(cls, memory: QuestionMemory) -> "MCPOAuthRoutingParams":
        return cls(
            account_id=memory.get_account_id(),
            agent_id=memory.get_agent_id(),
            workflow_id=memory.get_workflow_id(),
            session_id=memory.get_session_id(),
            question_id=memory.original_question_uuid,
            oauth_uuid=memory.original_question_uuid,
        )


@cache
def _get_mcp_fernet() -> Fernet:
    """Return a Fernet instance using the shared ENCRYPTION_SECRET_KEY env var."""
    from hyperforge.db.settings import EncryptionSettings

    settings = EncryptionSettings()
    return Fernet(settings.encryption_secret_key)


def encrypt_mcp_oauth_state(routing: MCPOAuthRoutingParams) -> str:
    """Encrypt routing context into a URL-safe Fernet token.

    The token embeds a TTL so that ``decrypt_mcp_oauth_state`` can reject
    tokens that arrive after ``_MCP_OAUTH_STATE_TTL`` seconds.

    Args:
        routing: MCPOAuthRoutingParams with all routing identifiers and sdk_state.

    Returns:
        A URL-safe string suitable for use as the OAuth ``state`` parameter.
    """
    f = _get_mcp_fernet()
    payload = routing.model_dump_json().encode()
    return f.encrypt(payload).decode()


def decrypt_mcp_oauth_state(token: str) -> MCPOAuthRoutingParams:
    """Decrypt and validate a Fernet-encrypted MCP OAuth state token.

    Args:
        token: The value of the ``state`` query parameter from the callback.

    Returns:
        The MCPOAuthRoutingParams originally passed to ``encrypt_mcp_oauth_state``.

    Raises:
        cryptography.fernet.InvalidToken: If the token is invalid, tampered,
            or older than ``_MCP_OAUTH_STATE_TTL`` seconds.
    """
    f = _get_mcp_fernet()
    payload = f.decrypt(token.encode(), ttl=_MCP_OAUTH_STATE_TTL)
    return MCPOAuthRoutingParams.model_validate_json(payload)


class _AcceptJsonOAuthClientProvider(OAuthClientProvider):
    """OAuthClientProvider that requests JSON from the token endpoint.

    Some OAuth servers default to returning tokens in
    URL-encoded form data format. Adding ``Accept: application/json`` makes them
    return standard JSON, which the MCP SDK expects.
    """

    async def _exchange_token_authorization_code(
        self,
        auth_code: str,
        code_verifier: str,
        *,
        token_data: dict[str, Any] | None = None,
    ) -> httpx.Request:
        req = await super()._exchange_token_authorization_code(
            auth_code, code_verifier, token_data=token_data
        )
        req.headers["Accept"] = "application/json"
        return req


class _RoutedOAuthClientProvider(_AcceptJsonOAuthClientProvider):
    """OAuthClientProvider that embeds routing context in the OAuth state parameter.

    Replaces the SDK-generated random ``state`` token with a Fernet-encrypted
    payload containing routing metadata (account_id, session_id, ...).  This
    allows the callback endpoint to reconstruct the NATS subject.
    Forked from MCP SDK's built-in OAuthClientProvider with the same overrides as the MCP SDK's AuthorizationCodeGrantProvider.
    """

    def __init__(
        self,
        *args: Any,
        routing: MCPOAuthRoutingParams,
        authorization_endpoint: str | None = None,
        token_endpoint: str | None = None,
        pkce: bool = True,
        single_flight_key: str | None = None,
        callback_handler_for_oauth_uuid: Callable[
            [str], Awaitable[tuple[str, str | None]]
        ]
        | None = None,
        **kwargs: Any,
    ) -> None:
        super().__init__(*args, **kwargs)
        self._routing = routing
        self._authorization_endpoint = authorization_endpoint
        # Keep token_endpoint separate - OASM discovery overwrites oauth_metadata on 401.
        self._token_endpoint = token_endpoint
        self._pkce = pkce
        self._single_flight_key = single_flight_key
        self._callback_handler_for_oauth_uuid = callback_handler_for_oauth_uuid
        self._pkce_grants: dict[str, tuple[str, str]] = {}
        if token_endpoint:
            # Seed oauth_metadata so refresh flows work before OASM discovery runs.
            existing = self.context.oauth_metadata
            self.context.oauth_metadata = OAuthMetadata(
                issuer=existing.issuer if existing else "https://placeholder.invalid",
                authorization_endpoint=(
                    existing.authorization_endpoint
                    if existing and existing.authorization_endpoint
                    else "https://placeholder.invalid/authorize"
                ),
                token_endpoint=token_endpoint,  # type: ignore[arg-type]
            )

    def _get_token_endpoint(self) -> str:
        """Use the manually configured endpoint, ignoring OASM discovery."""
        if self._token_endpoint:
            return self._token_endpoint
        return super()._get_token_endpoint()

    async def async_auth_flow(self, request: httpx.Request):
        if self._single_flight_key is None:
            auth_flow = super().async_auth_flow(request)
            try:
                auth_request = await auth_flow.__anext__()
                while True:
                    response = yield auth_request
                    auth_request = await auth_flow.asend(response)
            except StopAsyncIteration:
                return
            return

        lock = _get_single_flight_lock(self._single_flight_key)
        logger.info(
            "mcp_oauth single_flight_wait: key=%s",
            self._single_flight_key,
        )
        async with lock:
            logger.info(
                "mcp_oauth single_flight_enter: key=%s",
                self._single_flight_key,
            )
            auth_flow = super().async_auth_flow(request)
            try:
                auth_request = await auth_flow.__anext__()
                while True:
                    response = yield auth_request
                    auth_request = await auth_flow.asend(response)
            except StopAsyncIteration:
                return
            finally:
                logger.info(
                    "mcp_oauth single_flight_exit: key=%s",
                    self._single_flight_key,
                )

    async def _perform_authorization_code_grant(self) -> tuple[str, str]:
        """Override to use a Fernet-encrypted state instead of a random token."""
        if self.context.client_metadata.redirect_uris is None:
            raise OAuthFlowError(
                "No redirect URIs provided for authorization code grant"
            )
        if not self.context.redirect_handler:
            raise OAuthFlowError(
                "No redirect handler provided for authorization code grant"
            )
        if self._callback_handler_for_oauth_uuid is None:
            raise OAuthFlowError(
                "No callback handler provided for authorization code grant"
            )

        if self._authorization_endpoint:
            auth_endpoint = self._authorization_endpoint
        elif (
            self.context.oauth_metadata
            and self.context.oauth_metadata.authorization_endpoint
        ):
            auth_endpoint = str(self.context.oauth_metadata.authorization_endpoint)
        else:
            auth_base_url = self.context.get_authorization_base_url(
                self.context.server_url
            )
            auth_endpoint = auth_base_url + "/authorize"

        if not self.context.client_info:
            raise OAuthFlowError("No client info available for authorization")

        # Generate PKCE parameters and a random nonce that the SDK will verify.
        pkce_params = _generate_pkce_parameters()
        sdk_state = secrets.token_urlsafe(32)
        oauth_uuid = uuid4().hex
        verifier_fp = _fingerprint(pkce_params.code_verifier)
        challenge_fp = _fingerprint(pkce_params.code_challenge)

        # Encrypt routing context + grant identifiers into the OAuth state parameter.
        encrypted_state = encrypt_mcp_oauth_state(
            self._routing.model_copy(
                update={"oauth_uuid": oauth_uuid, "sdk_state": sdk_state}
            )
        )

        auth_params: dict[str, str] = {
            "response_type": "code",
            "client_id": self.context.client_info.client_id or "",
            "redirect_uri": str((self.context.client_metadata.redirect_uris or [])[0]),
            "state": encrypted_state,
        }
        if self._pkce:
            auth_params["code_challenge"] = pkce_params.code_challenge
            auth_params["code_challenge_method"] = "S256"
            self._pkce_grants[verifier_fp] = (oauth_uuid, challenge_fp)
            logger.info(
                "mcp_oauth pkce_grant_created: oauth_uuid=%s question_id=%s verifier_fp=%s challenge_fp=%s",
                oauth_uuid,
                self._routing.question_id,
                verifier_fp,
                challenge_fp,
            )

        if self.context.should_include_resource_param(self.context.protocol_version):
            auth_params["resource"] = self.context.get_resource_url()

        if self.context.client_metadata.scope:
            auth_params["scope"] = self.context.client_metadata.scope
            if "offline_access" in self.context.client_metadata.scope.split():
                auth_params["prompt"] = "consent"

        await self.context.redirect_handler(f"{auth_endpoint}?{urlencode(auth_params)}")

        # Wait for callback - the callback handler returns (code, sdk_state).
        auth_code, returned_state = await self._callback_handler_for_oauth_uuid(
            oauth_uuid
        )

        if returned_state is None or not secrets.compare_digest(
            returned_state, sdk_state
        ):
            raise OAuthFlowError(
                f"State parameter mismatch: {returned_state} != {sdk_state}"
            )

        if not auth_code:
            raise OAuthFlowError("No authorization code received")

        logger.info(
            "mcp_oauth authorization_grant_ready: oauth_uuid=%s question_id=%s pkce=%s verifier_fp=%s",
            oauth_uuid,
            self._routing.question_id,
            self._pkce,
            verifier_fp if self._pkce else "disabled",
        )
        return auth_code, pkce_params.code_verifier if self._pkce else ""

    async def _exchange_token_authorization_code(
        self,
        auth_code: str,
        code_verifier: str,
        *,
        token_data: dict[str, Any] | None = None,
    ) -> Any:
        """Override to skip code_verifier when PKCE is disabled."""
        if self._pkce:
            verifier_fp = _fingerprint(code_verifier)
            expected_oauth_uuid, expected_challenge_fp = self._pkce_grants.pop(
                verifier_fp, ("unknown", "unknown")
            )
            actual_challenge = _pkce_challenge_for_verifier(code_verifier)
            actual_challenge_fp = _fingerprint(actual_challenge)
            logger.info(
                "mcp_oauth token_exchange_pkce: oauth_uuid=%s question_id=%s verifier_fp=%s challenge_fp=%s expected_challenge_fp=%s match=%s",
                expected_oauth_uuid,
                self._routing.question_id,
                verifier_fp,
                actual_challenge_fp,
                expected_challenge_fp,
                expected_challenge_fp == actual_challenge_fp,
            )
            req = await super()._exchange_token_authorization_code(
                auth_code, code_verifier, token_data=token_data
            )
            logger.info(
                "mcp_oauth token_exchange_request_built: oauth_uuid=%s question_id=%s token_url=%s has_code_verifier=%s",
                expected_oauth_uuid,
                self._routing.question_id,
                req.url,
                "code_verifier=" in req.content.decode(errors="ignore"),
            )
            return req
        # PKCE disabled: build the token request without code_verifier.
        if not self.context.client_info:
            raise OAuthFlowError("Missing client info")
        token_url = self._get_token_endpoint()
        data: dict[str, str] = {
            "grant_type": "authorization_code",
            "code": auth_code,
            "redirect_uri": str((self.context.client_metadata.redirect_uris or [])[0]),
            "client_id": self.context.client_info.client_id or "",
        }
        headers = {"Content-Type": "application/x-www-form-urlencoded"}
        data, headers = self.context.prepare_token_auth(data, headers)
        return httpx.Request("POST", token_url, data=data, headers=headers)


def create_mcp_http_client(
    ca_cert: str | None = None,
    certificate: str | None = None,
    headers: dict[str, str] | None = None,
    timeout: httpx.Timeout | None = None,
    auth: httpx.Auth | None = None,
) -> httpx.AsyncClient:
    """Create a standardized httpx AsyncClient with MCP defaults.

    This function provides common defaults used throughout the MCP codebase:
    - follow_redirects=True (always enabled)
    - Default timeout of 30 seconds if not specified

    Args:
        headers: Optional headers to include with all requests.
        timeout: Request timeout as httpx.Timeout object.
            Defaults to 30 seconds if not specified.
        auth: Optional authentication handler.

    Returns:
        Configured httpx.AsyncClient instance with MCP defaults.

    Note:
        The returned AsyncClient must be used as a context manager to ensure
        proper cleanup of connections.

    Examples:
        # Basic usage with MCP defaults
        async with create_mcp_http_client() as client:
            response = await client.get("https://api.example.com")

        # With custom headers
        headers = {"Authorization": "Bearer token"}
        async with create_mcp_http_client(headers) as client:
            response = await client.get("/endpoint")

        # With both custom headers and timeout
        timeout = httpx.Timeout(60.0, read=300.0)
        async with create_mcp_http_client(headers, timeout) as client:
            response = await client.get("/long-request")

        # With authentication
        from httpx import BasicAuth
        auth = BasicAuth(username="user", password="pass")
        async with create_mcp_http_client(headers, timeout, auth) as client:
            response = await client.get("/protected-endpoint")
    """
    # Set MCP defaults
    kwargs: dict[str, Any] = {
        "follow_redirects": True,
    }

    # Handle timeout
    if timeout is None:
        kwargs["timeout"] = httpx.Timeout(200.0)
    else:
        kwargs["timeout"] = timeout

    # Handle headers
    if headers is not None:
        kwargs["headers"] = headers

    # Handle authentication
    if auth is not None:
        kwargs["auth"] = auth
    safe_transport: SafeTransport
    if ca_cert is not None or certificate is not None:
        ssl_context = ssl.create_default_context()
        if ca_cert is not None:
            ssl_context.load_verify_locations(cadata=ca_cert)

        if certificate is not None:
            if len(certificate) > 32_000:
                raise ValueError("Certificate is too large")
            with tempfile.NamedTemporaryFile(mode="w+", delete=False) as cert_file:
                cert_file.write(certificate)

            ssl_context.load_cert_chain(certfile=cert_file.name)

        safe_transport = SafeTransport(verify=ssl_context)
    else:
        safe_transport = SafeTransport()

    return httpx.AsyncClient(transport=safe_transport, **kwargs)


class FeedbackTokenStorage(TokenStorage):
    """Token storage that negotiates MCP credentials with the user via the Feedback mechanism.

    On ``get_tokens()``, asks the user for an existing Bearer token (15 s timeout).
    If none, returns ``None`` so the SDK starts the full OAuth flow.
    On ``set_tokens()``, notifies the user so they can store it client-side.
    Nothing is persisted server-side.
    """

    def __init__(
        self,
        memory: QuestionMemory,
        agent_id: str,
        uri: str,
        client_id: Optional[str],
        client_secret: Optional[str],
        redirect_uris: list[str],
        grant_types: list[str],
        response_types: list[str],
        scope: Optional[str],
    ) -> None:
        self._memory = memory
        self._agent_id = agent_id
        self._uri = uri
        self._client_info: OAuthClientInformationFull | None = None
        if client_id is not None:
            self._client_info = OAuthClientInformationFull(
                client_id=client_id,
                client_secret=client_secret,
                token_endpoint_auth_method="client_secret_post"
                if client_secret
                else "none",
                client_name="Hyperforge MCP Client",
                redirect_uris=[AnyUrl(x) for x in redirect_uris],
                grant_types=grant_types,
                response_types=response_types,
                scope=scope,
            )

    async def get_tokens(self) -> OAuthToken | None:
        """Ask the user for an existing Bearer token (15 s timeout).

        Returns the token if provided, or None to let the SDK start the OAuth flow.
        """
        logger.info(
            "mcp_oauth get_tokens: asking client for cached credentials; uri=%s agent=%s session=%s",
            self._uri,
            self._agent_id,
            self._memory.get_session_id(),
        )
        feedback = Feedback(
            request_id=self._memory.get_session_id(),
            question="Get credentials",
            data=None,
            get_credentials={self._uri: Provider.MCP_OAUTH},
            module="oauth",
            agent_id=self._agent_id,
            response_schema=OAuthFeedbackReturnSchema.model_json_schema(),
            # Give the client 60 s to reply before assuming "no credentials"
            # and starting OAuth automatically.
            timeout_ms=60_000,
        )
        try:
            answer = await asyncio.wait_for(
                self._memory.send_feedback(feedback), timeout=61.0
            )
        except (asyncio.TimeoutError, asyncio.CancelledError, Exception) as exc:
            logger.info(
                "mcp_oauth get_tokens: no answer from client (timeout/cancel); uri=%s reason=%s",
                self._uri,
                type(exc).__name__,
            )
            answer = None
        if answer is not None:
            try:
                schema = OAuthFeedbackReturnSchema.model_validate_json(answer.response)
                if schema.existing_credentials:
                    creds = schema.existing_credentials.get(self._uri, {})
                    access_token = creds.get("access_token")
                    if access_token:
                        logger.info(
                            "mcp_oauth get_tokens: cached token found; uri=%s agent=%s",
                            self._uri,
                            self._agent_id,
                        )
                        return OAuthToken(
                            access_token=access_token, token_type="Bearer"
                        )
            except Exception:
                pass
        logger.info(
            "mcp_oauth get_tokens: no cached token - starting full OAuth flow; uri=%s agent=%s",
            self._uri,
            self._agent_id,
        )
        return None

    async def set_tokens(self, tokens: OAuthToken) -> None:
        """Notify the WS client of the new token before the SDK retries.

        We await directly so the feedback is delivered before the SDK
        continues - a fire-and-forget task gets cancelled during MCP
        transport teardown and never reaches the WebSocket client.
        """
        logger.info(
            "mcp_oauth set_tokens: sending new token to WS client; uri=%s agent=%s session=%s",
            self._uri,
            self._agent_id,
            self._memory.get_session_id(),
        )
        feedback = Feedback(
            request_id=self._memory.get_session_id(),
            question="Send credentials",
            data=None,
            credentials={
                self._uri: {
                    "access_token": tokens.access_token,
                    "token_type": tokens.token_type,
                }
            },
            module="oauth",
            agent_id=self._agent_id,
            response_schema=OAuthFeedbackReturnSchema.model_json_schema(),
            # Give the client time to ACK. The SDK waits for set_tokens
            # to return before retrying the MCP request, so up to 60 s
            # is acceptable; the client can ACK immediately.
            timeout_ms=60_000,
        )
        try:
            await asyncio.wait_for(self._memory.send_feedback(feedback), timeout=61.0)
            logger.info(
                "mcp_oauth set_tokens: token delivered to WS client; uri=%s agent=%s",
                self._uri,
                self._agent_id,
            )
        except (asyncio.TimeoutError, asyncio.CancelledError, Exception) as exc:
            logger.warning(
                "mcp_oauth set_tokens: failed to deliver token (ACK optional); uri=%s reason=%s",
                self._uri,
                type(exc).__name__,
            )

    async def get_client_info(self) -> OAuthClientInformationFull | None:
        return self._client_info

    async def set_client_info(self, client_info: OAuthClientInformationFull) -> None:
        self._client_info = client_info


async def handle_redirect(memory: QuestionMemory, auth_url: str) -> None:
    """Send the OAuth authorization URL to the user.

    The routing context is already embedded in the ``state`` parameter of
    ``auth_url`` as a Fernet-encrypted token - no in-process registration
    is needed here.
    """
    logger.info(
        "mcp_oauth handle_redirect: sending OAuth URL to user; agent=%s session=%s",
        memory.get_agent_id(),
        memory.get_session_id(),
    )
    await memory.send_oauth(oauth=OAuthAuthenticateURL(oauth_url=auth_url))
    logger.info(
        "mcp_oauth handle_redirect: OAuth URL delivered, waiting for user to authenticate; agent=%s session=%s",
        memory.get_agent_id(),
        memory.get_session_id(),
    )


async def handle_callback(
    memory: QuestionMemory, module: str, agent_id: str, oauth_uuid: str
) -> tuple[str, str | None]:
    has_fn = getattr(memory, "oauth_callback_fn", None) is not None
    logger.info(
        "mcp_oauth handle_callback: waiting for OAuth callback; agent=%s session=%s question_id=%s oauth_uuid=%s has_oauth_fn=%s",
        agent_id,
        memory.get_session_id(),
        memory.original_question_uuid,
        oauth_uuid,
        has_fn,
    )
    callback_payload = await memory.recv_oauth_callback(
        question_id=memory.original_question_uuid,
        oauth_uuid=oauth_uuid,
    )
    if callback_payload:
        if "://" in callback_payload:
            params = parse_qs(urlparse(callback_payload).query)
        else:
            params = parse_qs(callback_payload.lstrip("?"))

        if "error" in params:
            err = params["error"][0]
            desc = params.get("error_description", [""])[0]
            logger.error(
                "mcp_oauth handle_callback: OAuth error from provider; agent=%s error=%s desc=%s",
                agent_id,
                err,
                desc,
            )
            raise ValueError(f"OAuth authorization failed: {err} {desc}".strip())

        if "code" not in params:
            logger.error(
                "mcp_oauth handle_callback: callback payload missing code; agent=%s payload_keys=%s",
                agent_id,
                list(params.keys()),
            )
            raise ValueError(
                "OAuth callback payload does not include authorization code"
            )

        logger.info(
            "mcp_oauth handle_callback: authorization code received ok; agent=%s session=%s",
            agent_id,
            memory.get_session_id(),
        )
        return params["code"][0], params.get("state", [None])[0]
    else:
        logger.error(
            "mcp_oauth handle_callback: no callback payload received (timeout?); agent=%s session=%s",
            agent_id,
            memory.get_session_id(),
        )
        raise ValueError("No OAuth callback payload received")


@driver(
    id="mcphttp",
    title="MCP HTTP Driver",
    description="Driver for interacting with the MCP HTTP API.",
    config_schema=MCPHTTPDriverConfig,
)
class MCPHTTPDriver(Driver):
    config: MCPHTTPInnerConfig
    auth: Optional[Auth] = None

    @classmethod
    async def init(cls, driver: MCPHTTPDriverConfig) -> "MCPHTTPDriver":
        obj = cls(
            config=driver.config,
            name=driver.name,
            provider=driver.provider,
        )

        # TODO: Implement basic auth ?

        return obj

    def client(
        self,
        memory: QuestionMemory,
        module: str,
        agent_id: str,
        request_id,
        headers: Optional[dict[str, str]] = None,
    ):
        # Returns the HTTP client context manager
        new_headers = {}
        new_headers.update(self.config.headers)
        if headers is not None:
            new_headers.update(headers)

        if self.config.auth_server_url is not None:
            routing = MCPOAuthRoutingParams.from_memory(memory)
            storage = FeedbackTokenStorage(
                memory=memory,
                agent_id=agent_id,
                uri=self.config.uri,
                client_id=self.config.client_id,
                client_secret=self.config.client_secret,
                redirect_uris=self.config.redirect_uris,
                grant_types=self.config.grant_types,
                response_types=self.config.response_types,
                scope=self.config.scope,
            )
            auth: Auth | None = _RoutedOAuthClientProvider(
                server_url=self.config.auth_server_url,
                client_metadata=OAuthClientMetadata(
                    client_name="Hyperforge MCP Client",
                    redirect_uris=[AnyUrl(x) for x in self.config.redirect_uris],
                    grant_types=self.config.grant_types,
                    response_types=self.config.response_types,
                    scope=self.config.scope,
                ),
                storage=storage,
                routing=routing,
                authorization_endpoint=self.config.authorization_endpoint,
                token_endpoint=self.config.token_endpoint,
                pkce=self.config.pkce,
                single_flight_key=(
                    f"{routing.account_id}.{routing.agent_id}."
                    f"{routing.workflow_id}.{routing.session_id}."
                    f"{routing.question_id}.{self.config.uri}"
                ),
                redirect_handler=partial(handle_redirect, memory),
                callback_handler_for_oauth_uuid=partial(
                    handle_callback,
                    memory,
                    module,
                    agent_id,
                ),
            )
        else:
            auth = self.auth

        client = create_mcp_http_client(
            self.config.ca_certificate,
            self.config.crt_certificate,
            new_headers,
            Timeout(self.config.timeout),
            auth,
        )
        return streamable_http_client(self.config.uri, http_client=client)

    async def sse_reader(self):
        pass

    async def post_writer(self):
        pass

    async def initialize(self):
        pass

    async def finalize(self):
        pass
